#define INICIO	               257
#define FIN 	               258
#define LEER 	               259
#define ESCRIBIR		         260
#define SI  		            261
#define ENTONCES   	         262
#define SI_NO     	         263
#define FIN_SI     	         264
#define MIENTRAS    	         265
#define HACER     	         266
#define FIN_MIENTRAS          267
#define REPETIR     	         268
#define HASTA_QUE   	         269
#define PARA       	         270
#define DESDE     	         271
#define HASTA     	         272
#define PASO        	         273
#define FIN_PARA   	         274
#define ID		               275
#define NUMERO		            276
#define COMILLA               277
#define SUMA                  278
#define RESTA                 279
#define PRODUCTO              280
#define DIVISION              281
#define MODULO                282
#define POTENCIA              283
#define CONCATENACION         284
#define MENOR_QUE             285
#define MENOR_IGUAL_QUE       286
#define MAYOR_QUE             287
#define MAYOR_IGUAL_QUE       288
#define IGUAL                 289
#define DISTINTO              290
#define DISYUNCION_LOGICA     291
#define CONJUNCION_LOGICA     292
#define NEGACION_LOGICA       293
#define FIN_SENTENCIA         294
#define PARENTESIS_IZQUIERDO  295
#define PARENTESIS_DERECHO    296
#define ASIGNACION            297
#define ALMOHADILLA           298
#define MOD                   299
